domain: cloud-init.io

image: prod-comms.ps5.docker-registry.canonical.com/cloud-init.io

useProxy: false

readinessPath: "/"

extraHosts:
  - domain: cloud-init.org
    useParentTLS: True

env:
  - name: COOKIE_SERVICE_API_KEY
    secretKeyRef:
      key: cookies-api-key
      name: cookies-canonical-com-credentials

# Overrides for production
production:
  replicas: 5
  nginxConfigurationSnippet: |
    if ($host != 'cloud-init.io' ) {
      rewrite ^ https://cloud-init.io$request_uri? permanent;
    }
    more_set_headers "Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect";

# Overrides for staging
staging:
  replicas: 3
  nginxConfigurationSnippet: |
    more_set_headers "X-Robots-Tag: noindex";
    more_set_headers "Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect";
